name: Deploy static content to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer
        run: composer self-update --2

      - name: Install Dependencies
        run: composer update

      - name: Run crawler.php
        run: php crawler.php

      - name: Commit and Push changes
        run: |
          git diff
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update Videos" || exit 0
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            !vendor/
            **/*

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
